agents:
  queue: timvel-agent-1

steps:
  - label: "Build docker image"
    key: step-1
    command: sh docker-build-prod.sh

  - wait

  - label: "Build web"
    key: step-2
    command: 
      - sh docker-compose-up.sh
      - node ./scripts/logDir.js

  - label: "Cleanup docker"
    command: 
      - sh ./scripts/docker-cleanup.sh