agents:
  queue: timvel-agent-1

steps:
  - name: "step 1:"
    key: step-1
    parallelism: 5
    command: "sh scripts/run.sh"

  - name: "step 3:"
    key: step-3
    parallelism: 5
    command: "echo step3"

  - name: "step 4:"
    depends_on: step-3
    command: "echo step4 depends on step3"

  - name: "step 5:"
    depends_on: step-1
    command: "echo step5 depends on step1"

  - wait

  - name: "step 2:"
    label: "label 2"
    command: "echo step2"
