agents:
  queue: timvel-agent-1

steps:
  - label: "log Env"
    command: 
    - source ~/.bashrc
    - sh ./scripts/run.sh

  - label: "Build docker image"
    key: step-1
    command: sh docker-build-prod.sh

  - wait
  
  - label: "Build web"
    key: step-2
    command: "sh docker-compose-up.sh"

  - wait
