agents:
  queue: timvel-agent-1

steps:
  - label: "Pull or install node modules"
    plugins:
      - ecr#v2.7.0:
            login: true
      - seek-oss/docker-ecr-cache#v2.0.0: # https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin
          cache-on:
            - package.json # avoid cache hits on stale lockfiles
            - package-lock.json
          dockerfile: docker/node_modules.dockerfile
          context: ..
          max-age-days: 7
          ecr-name: ${AWS_ECR_REPOSITORY_URI}/build-cache/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}
          region: ${AWS_ECR_REGION}
            
  - wait

  - label: "Build docker image"
    key: step-1
    command: sh docker-build-prod.sh

  - wait

  - label: "Build web"
    key: step-2
    command: 
      - sh docker-compose-up.sh
      - node ./scripts/logDir.js

  - label: "Cleanup docker"
    command: 
      - sh ./scripts/docker-cleanup.sh