agents:
  queue: timvel-agent-1

steps:
  - label: "Build docker image"
    command:
      - echo "done"
      - sh docker-build-prod.sh
    plugins:
      - ecr#v2.7.0: # https://github.com/buildkite-plugins/ecr-buildkite-plugin
          login: true
          # account-ids: "603299253693"
          # region: "${AWS_ECR_REGION}"
          # assume_role:
          #   role_arn: "arn:aws:iam::603299253693:user/pipeline_ecr_cache"
      - seek-oss/docker-ecr-cache#v2.0.0: # https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin
          cache-on:
            - package.json # avoid cache hits on stale lockfiles
            - package-lock.json
          dockerfile: docker/node_modules.dockerfile
          context: "."
          max-age-days: 7
          ecr-name: "build-cache/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}"
          region: "${AWS_ECR_REGION}"

  - wait

  - label: "Build web"
    key: step-2
    command:
      - sh docker-compose-up.sh
      - node ./scripts/logDir.js

  - label: "Cleanup docker"
    command:
      - sh ./scripts/docker-cleanup.sh
