version: '3'
services:
  web:
    image: playground/buildkite
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    entrypoint: docker-entrypoint.sh
    working_dir: /app/public
    command: [ "ls" ]
